name: motokosan
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16
  firebase_storage: ^3.1.6
  provider: ^4.3.2
  shared_preferences: ^0.5.8
  random_string: ^2.1.0
  intl: ^0.16.1
  sqflite: ^1.3.1
  path_provider: any
  #path: ^1.7.0
  soundpool: ^1.1.1

  native_pdf_view: ^3.8.0
  #numberpicker: ^1.2.1
  image_picker: ^0.6.7+7
  flutter_native_image: ^0.0.5+2
  photo_view: ^0.10.2
  font_awesome_flutter: ^8.8.1
  percent_indicator: ^2.1.6
  flare_flutter: ^2.0.6
  awesome_dialog: ^1.2.0
  youtube_player_flutter: ^7.0.0+7
  uuid: ^2.2.2
  webview_flutter: ^1.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/pdfs/
    - assets/flr/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
